pyfuze main.py `
    --output-name pixabay-schema.exe `
    --pyproject pyproject.toml `
    --uv-lock uv.lock `
    --python $(Get-Content -Path .python-version) `
    --mode online `
    --env UV_PYTHON_INSTALL_MIRROR=https://gh-proxy.com/github.com/astral-sh/python-build-standalone/releases/download `
    --env UV_DEFAULT_INDEX=https://mirrors.aliyun.com/pypi/simple `
    --env UV_INSTALLER_GITHUB_BASE_URL=https://gh-proxy.com/https://github.com `
    --uv-install-script-windows https://cors.isteed.cc/https://astral.sh/uv/install.ps1 `
    --uv-install-script-unix https://cors.isteed.cc/https://astral.sh/uv/install.sh
